### PR TITLE
Migrate to jsbundling usage

### PR DESCRIPTION
**Pull request by jho406**
This updates Humid to use jsbundling instead of webpacker. Moving forward, we have to specify the build path of the SSR entry point. This mimics the position that js-bundling takes where we let the tool build the file at the cost of hot reloading.

In the process we also move over to github actions.

### CODE REVIEW

**Comment by justin808** [comment]
Why are you not using ShakaPacker?

**Comment by jho406** [comment]
Hi. Thanks for commenting. Do you have a compelling reason to share to use ShakaPacker?

**Comment by justin808** [comment]
There are many subtleties of configuration embedded in Shakapacker. It's grown a lot since the Webpacker days. It's the Rails "Convention over Configuration" principle. If you use jsbundling-rails, you'll have lots of configuration!

**Comment by jho406** [comment]
Ahh i see the confusion here. This PR is about taking a neutral stance on javascript bundling. You're welcome to use whatever you want, Humid just expects a path to some bundled file. This comes at the cost of the lack of hot-reloading, but that could be something we add in the future as a hook or something else.

**Comment by justin808** [comment]
I suggest you create clear explanations for decisions, or else it will seem like a lot of reinventing the wheel compared to shakapacker (and the [react_on_rails](https://github.com/ShakaCode/react_on_rails) gem)

**Comment by jho406** [comment]
> I suggest you create clear explanations for decisions

Certainly. 

> it will seem like a lot of reinventing the wheel compared to shakapacker (and the [react_on_rails](https://github.com/ShakaCode/react_on_rails) gem)

Just so I understand, you had concerns that my project was possibly overlapping with shakapacker (and the react_on_rails gem)? What makes it a concern for you?

**Comment by justin808** [comment]
Here's a good example discussion regarding whether or not to use Shakapacker: https://github.com/decidim/decidim/discussions/8783#discussioncomment-2104076

Eventually, the move was made.

**Comment by jho406** [comment]
What about that thread do you feel is relevant for Humid? As I mentioned before, Humid, in its current state, doesn't care what bundling solution you use. It operates on a post processed file (typically a built application.js).

**Pull request merged**
